version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-cd
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /opt/homebrew/bin/docker:/opt/homebrew/bin/docker
    user: root
    restart: unless-stopped
    privileged: true
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    group_add:
      - 999
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  jenkins_home:
